{% set name = "sympy" %}
{% set version = "1.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d3d3fe8df1e5a0b42f0e7bdf50541697dbe7d23746e894990c030e2b05e72517

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir --no-build-isolation -vvv
  entry_points:
    - isympy = isympy:main

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - mpmath >=1.1.0,<1.4
    # gmpy2 brings added performance. https://github.com/sympy/sympy/blob/1.14.0/doc/src/contributing/dependencies.md#recommended-optional-dependencies
    - gmpy2
  run_constrained:
    # LaTeX Parser/Lexer. https://github.com/sympy/sympy/blob/1.14.0/doc/src/modules/parsing.rst#runtime-installation
    - antlr-python-runtime >=4.11,<4.12
    - hypothesis >=6.70.0
test:
  imports:
    - sympy
    - sympy.abc
    - sympy.release
    - sympy.algebras
    - sympy.assumptions
    - sympy.assumptions.handlers
    - sympy.assumptions.predicates
    - sympy.assumptions.relation
    - sympy.benchmarks
    - sympy.calculus
    - sympy.categories
    - sympy.codegen
    - sympy.combinatorics
    - sympy.concrete
    - sympy.core
    - sympy.core.benchmarks
    - sympy.crypto
    - sympy.diffgeom
    - sympy.discrete
    - sympy.external
    - sympy.functions
    - sympy.functions.combinatorial
    - sympy.functions.elementary
    - sympy.functions.elementary.benchmarks
    - sympy.functions.special
    - sympy.functions.special.benchmarks
    - sympy.geometry
    - sympy.holonomic
    - sympy.integrals
    - sympy.integrals.benchmarks
    - sympy.interactive
    - sympy.liealgebras
    - sympy.logic
    - sympy.logic.algorithms
    - sympy.logic.utilities
    - sympy.matrices
    - sympy.matrices.benchmarks
    - sympy.matrices.expressions
    - sympy.multipledispatch
    - sympy.ntheory
    - sympy.parsing
    - sympy.parsing.autolev
    - sympy.parsing.autolev._antlr
    - sympy.parsing.c
    - sympy.parsing.fortran
    - sympy.parsing.latex
    - sympy.parsing.latex._antlr
    - sympy.physics
    - sympy.physics.continuum_mechanics
    - sympy.physics.control
    - sympy.physics.hep
    - sympy.physics.mechanics
    - sympy.physics.optics
    - sympy.physics.quantum
    - sympy.physics.units
    - sympy.physics.units.definitions
    - sympy.physics.units.systems
    - sympy.physics.vector
    - sympy.plotting
    - sympy.plotting.intervalmath
    - sympy.plotting.pygletplot
    - sympy.polys
    - sympy.polys.agca
    - sympy.polys.benchmarks
    - sympy.polys.domains
    - sympy.polys.matrices
    - sympy.printing
    - sympy.printing.pretty
    - sympy.sandbox
    - sympy.series
    - sympy.series.benchmarks
    - sympy.sets
    - sympy.sets.handlers
    - sympy.simplify
    - sympy.solvers
    - sympy.solvers.benchmarks
    - sympy.solvers.diophantine
    - sympy.solvers.ode
    - sympy.stats
    - sympy.stats.sampling
    - sympy.strategies
    - sympy.strategies.branch
    - sympy.tensor
    - sympy.tensor.array
    - sympy.tensor.array.expressions
    - sympy.testing
    - sympy.unify
    - sympy.utilities
    - sympy.utilities._compilation
    - sympy.utilities.mathml
    - sympy.vector
  requires:
    - pip
    - pytest >=7.1.0
    - pytest-xdist
    - hypothesis >=6.70.0
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - isympy --help

about:
  home: https://www.sympy.org
  license: BSD-3-Clause AND MIT
  license_family: BSD
  license_file:
    - LICENSE
    - sympy/parsing/latex/LICENSE.txt
    - data/TeXmacs/LICENSE
  summary: Python library for symbolic mathematics
  description: |
    SymPy is a Python library for symbolic mathematics. It aims to become a
    full-featured computer algebra system (CAS) while keeping the code as
    simple as possible in order to be comprehensible and easily extensible.
  doc_url: https://docs.sympy.org/latest/index.html
  dev_url: https://github.com/sympy/sympy

extra:
  recipe-maintainers:
    - asmeurer
    - msarahan
    - scopatz
    - isuruf