{% set version = "1.5" %}

package:
  name: sympy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sympy/sympy-{{ version }}.tar.gz
  sha256: 31567dc010bff0967ef7a87210acf3f938c6ab24481581fc143536fb103e9ce8

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - isympy = isympy:main

requirements:
  host:
    - fastcache
    - mpmath
    - pip
    - python
  run:
    - fastcache
    - setuptools
    - mpmath >=0.19
    - python
    - gmpy2 >=2.0.8   # [not win]

test:
  commands:
    - isympy --help
  imports:
    - sympy

about:
  home: http://sympy.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python library for symbolic mathematics
  description: |
    SymPy is a Python library for symbolic mathematics. It aims to become a
    full-featured computer algebra system (CAS) while keeping the code as
    simple as possible in order to be comprehensible and easily extensible.
  doc_url: http://docs.sympy.org/latest/index.html
  dev_url: https://github.com/sympy/sympy

extra:
  recipe-maintainers:
    - asmeurer
    - msarahan
    - scopatz
