{% set name = "sympy" %}
{% set version = "1.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d3d3fe8df1e5a0b42f0e7bdf50541697dbe7d23746e894990c030e2b05e72517

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir --no-build-isolation -vvv
  entry_points:
    - isympy = isympy:main

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - mpmath >=1.1.0,<1.4
    # gmpy2 brings added performance. https://github.com/sympy/sympy/blob/1.14.0/doc/src/contributing/dependencies.md#recommended-optional-dependencies
    - gmpy2
  run_constrained:
    # LaTeX Parser/Lexer. https://github.com/sympy/sympy/blob/1.14.0/doc/src/modules/parsing.rst#runtime-installation
    - antlr-python-runtime >=4.11,<4.12
    - hypothesis >=6.70.0
test:
  imports:
    - sympy
    - sympy.abc
    - sympy.algebras
    - sympy.assumptions
    - sympy.calculus
    - sympy.categories
    - sympy.codegen
    - sympy.combinatorics
    - sympy.concrete
    - sympy.core
    - sympy.crypto
    - sympy.diffgeom
    - sympy.discrete
    - sympy.external
    - sympy.functions
    - sympy.geometry
    - sympy.holonomic
    - sympy.integrals
    - sympy.interactive
    - sympy.liealgebras
    - sympy.logic
    - sympy.matrices
    - sympy.multipledispatch
    - sympy.ntheory
    - sympy.parsing
    - sympy.physics
    - sympy.plotting
    - sympy.polys
    - sympy.printing
    - sympy.release
    - sympy.sandbox
    - sympy.series
    - sympy.sets
    - sympy.simplify
    - sympy.solvers
    - sympy.stats
    - sympy.strategies
    - sympy.tensor
    - sympy.unify
    - sympy.utilities
    - sympy.vector
  requires:
    - pip
    - pytest>=7.1.0
    - pytest-xdist
    - hypothesis
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - isympy --help

about:
  home: https://www.sympy.org
  license: BSD-3-Clause AND MIT
  license_family: OTHER
  license_file:
    - LICENSE
    - sympy/parsing/latex/LICENSE.txt
    - data/TeXmacs/LICENSE
  summary: Python library for symbolic mathematics
  description: |
    SymPy is a Python library for symbolic mathematics. It aims to become a
    full-featured computer algebra system (CAS) while keeping the code as
    simple as possible in order to be comprehensible and easily extensible.
  doc_url: https://docs.sympy.org/latest/index.html
  dev_url: https://github.com/sympy/sympy

extra:
  recipe-maintainers:
    - asmeurer
    - msarahan
    - scopatz
    - isuruf