{% set name = "sympy" %}
{% set version = "1.13.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sympy/sympy-{{ version }}.tar.gz
  sha256: 401449d84d07be9d0c7a46a64bd54fe097667d5e7181bfe67ec777be9e01cb13

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir --no-build-isolation -vvv
  entry_points:
    - isympy = isympy:main

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - mpmath >=0.19
    - python
    # gmpy2 brings added performance. It is not yet available for 3.12.
    - gmpy2 >=2.0.8   # [not py==312]
  run_constrained:
    # LaTeX Parser/Lexer
    - antlr-python-runtime >=4.7,<4.8
    - gmpy2 >=2.0.8

test:
  requires:
    - pip
    - pytest
    - pytest-xdist
    - hypothesis
  commands:
    - pip check
    - isympy --help
    - python -c "import sympy; sympy.test(parallel=True)"
  imports:
    - sympy
    - sympy.algebras
    - sympy.assumptions
    - sympy.assumptions.handlers
    - sympy.assumptions.predicates
    - sympy.assumptions.relation
    - sympy.benchmarks
    - sympy.calculus
    - sympy.categories
    - sympy.codegen
    - sympy.combinatorics
    - sympy.concrete
    - sympy.core
    - sympy.core.benchmarks
    - sympy.crypto
    - sympy.diffgeom
    - sympy.discrete
    - sympy.external
    - sympy.functions
    - sympy.functions.combinatorial
    - sympy.functions.elementary
    - sympy.functions.elementary.benchmarks
    - sympy.functions.special
    - sympy.functions.special.benchmarks
    - sympy.geometry
    - sympy.holonomic
    - sympy.integrals
    - sympy.integrals.benchmarks
    - sympy.interactive
    - sympy.liealgebras
    - sympy.logic
    - sympy.logic.algorithms
    - sympy.logic.utilities
    - sympy.matrices
    - sympy.matrices.benchmarks
    - sympy.matrices.expressions
    - sympy.multipledispatch
    - sympy.ntheory
    - sympy.parsing
    - sympy.parsing.autolev
    - sympy.parsing.autolev._antlr
    - sympy.parsing.c
    - sympy.parsing.fortran
    - sympy.parsing.latex
    - sympy.parsing.latex._antlr
    - sympy.physics
    - sympy.physics.continuum_mechanics
    - sympy.physics.control
    - sympy.physics.hep
    - sympy.physics.mechanics
    - sympy.physics.optics
    - sympy.physics.quantum
    - sympy.physics.units
    - sympy.physics.units.definitions
    - sympy.physics.units.systems
    - sympy.physics.vector
    - sympy.plotting
    - sympy.plotting.intervalmath
    - sympy.plotting.pygletplot
    - sympy.polys
    - sympy.polys.agca
    - sympy.polys.benchmarks
    - sympy.polys.domains
    - sympy.polys.matrices
    - sympy.printing
    - sympy.printing.pretty
    - sympy.sandbox
    - sympy.series
    - sympy.series.benchmarks
    - sympy.sets
    - sympy.sets.handlers
    - sympy.simplify
    - sympy.solvers
    - sympy.solvers.benchmarks
    - sympy.solvers.diophantine
    - sympy.solvers.ode
    - sympy.stats
    - sympy.stats.sampling
    - sympy.strategies
    - sympy.strategies.branch
    - sympy.tensor
    - sympy.tensor.array
    - sympy.tensor.array.expressions
    - sympy.testing
    - sympy.unify
    - sympy.utilities
    - sympy.utilities._compilation
    - sympy.utilities.mathml
    - sympy.vector

about:
  home: https://www.sympy.org
  license: BSD-3-Clause AND MIT
  license_family: BSD
  license_file:
    - LICENSE
    - sympy/parsing/latex/LICENSE.txt
    - data/TeXmacs/LICENSE
  summary: Python library for symbolic mathematics
  description: |
    SymPy is a Python library for symbolic mathematics. It aims to become a
    full-featured computer algebra system (CAS) while keeping the code as
    simple as possible in order to be comprehensible and easily extensible.
  doc_url: https://docs.sympy.org/latest/index.html
  dev_url: https://github.com/sympy/sympy

extra:
  recipe-maintainers:
    - asmeurer
    - msarahan
    - scopatz
    - isuruf
