travis:
  secure:
    BINSTAR_TOKEN: Z7lvhFYUNhXfmp4cPxhGyJPVOGhtlYKgnMEKq371DUr4avDsIJSdMWKuJ0KFKiSkYoa2/KIVwatf6eWJijqaGh+A30FbWffXmKQoB+qT8G5nzfEwh6xiP90C8Gzkhi5a2KbDeP9RMMuK13+61EcI2HzGgUoYhODiFPu1+Gvp9Qx6vDcziIYklZexnYm0UbdxMxqEPWijlTWvVNcK+l0d+8MDQ8uDI4oCrNVheEsPMC5Bn4PBSuQ1FQrbltKDsn8KZTyw2K1pW/mCfEBwuT05V+W0GmfdcPO40x/tv/uKx9KufIj+nQ5oP7WefE0gbgeyoPr+ZIT7oKx+H+OP71ABlHTbtD7dO9xmjtLXpc3O6NDRalvFYiyPRyRRE7URRo8oyiQMeR8C9jRhWJZiYCkonu0QJQmn4ZDNp6Nwir67E8BbLojRAUF5+i7evT/9YemSMw+PJDyNNQwL1+zd0egZgNmB1PNESz+CkD1fpwfKlEghlCbJvo7l6G0JPFaVuh0LOqqsXCxAP8QzK3RL2RiEy/A5H2iAoE0G/EBRavXdZr1MT5dRcTgNJ/MeoUe6ft4tLxxc7KK0YuMszDtPdnEWo7GrfoG1xbYsiAKiRNkNKn8nZsJOs5McxJAUr8t87R9Zo/gKAV6RtoSgis0LQ8T1jq7dnzenpeK1YlWWUTtTs5I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
